# This is a basic workflow to help you get started with Actions
name: DEPLOY

on:
  push:
    branches: [ "master" ]
    paths: ['src/**']
  pull_request:
    branches: [ "master" ]
    paths: ['src/**']
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run npm ci
        run: npm ci
      - name: npm run build
        run: npm run build
      - name: Zip Folder
        run: zip -r release.zip .
      - name: setup dist
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: ./release.zip
            
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: backend-build
          path: .
      - name: unzip
        run: unzip -o ./release.zip
      - name: start the app
        run: pm2 start
        
