# This is a basic workflow to help you get started with Actions
name: DEPLOY

on:
  push:
    branches: [ "master" ]
    paths: ['src/**']
  pull_request:
    branches: [ "master" ]
    paths: ['src/**']
  workflow_dispatch:


jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: run npm ci
        run: npm ci
      - name: npm run build
        run: npm run build
      - name: start the app
        run: pm2 start
